version: '3.8'
services:
  qsmith:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: qsmith
    container_name: qsmith
    working_dir: /app
    volumes:
      - ./app:/qsmith/app
      - ./alembic:/qsmith/alembic
      - ./.env:/qsmith/.env
    ports:
      - "9082:9082"
    environment:
      - PYTHONPATH=/app
