version: '3.8'
services:
  qsmith:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
        - DATABASE_URL=postgresql://postgres:password@host.docker.internal:5432/qsmith
        - HOST_IP=host.docker.internal
    ports:
      - "9082:9082"
      - "5678:5678"
    image: qsmith
    container_name: qsmith
    working_dir: /app
    volumes:
      - ./app:/qsmith/app
      - ./alembic:/qsmith/alembic
      - ./.env:/qsmith/.env
    entrypoint: [ "sh", "-c" ]
    command:
      [
        "pip install debugpy && python  -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 -m uvicorn main:app --host 0.0.0.0 --port 9082 --reload"
      ]
